/* JOIN TABLE for MANY-TO-MANY relationship*/
CREATE TABLE APP_USER_USER_PROFILE
(
    USER_ID         INT NOT NULL,
    USER_PROFILE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, USER_PROFILE_ID),
    CONSTRAINT FK_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID),
    CONSTRAINT FK_USER_PROFILE FOREIGN KEY (USER_PROFILE_ID) REFERENCES USER_PROFILE (ID)
);

/* Populate JOIN Table */
INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'bill'
  AND p.TYPE = 'USER';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'danny'
  AND p.TYPE = 'USER';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'sam'
  AND p.TYPE = 'ADMIN';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'nicole'
  AND p.TYPE = 'DBA';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'kenny'
  AND p.TYPE = 'ADMIN';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'kenny'
  AND p.TYPE = 'DBA';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'sudo'
  AND p.TYPE = 'USER';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'sudo'
  AND p.TYPE = 'ADMIN';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'sudo'
  AND p.TYPE = 'DBA';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'tsuser'
  AND p.TYPE = 'USER';

INSERT INTO APP_USER_USER_PROFILE (USER_ID, USER_PROFILE_ID)
SELECT u.ID,
       p.ID
FROM APP_USER u,
     USER_PROFILE p
WHERE u.SSO_ID = 'admin'
  AND p.TYPE = 'ADMIN';
