UPDATE APP_USER
SET PASSWORD = '$2a$10$2bjguGIOF59iJjp2.TFvL.Qe2VXeLzVCxcD5yOv.DNrrlgTZPEUai'
where SSO_ID = 'bill';

UPDATE APP_USER
SET PASSWORD = '$2a$10$V5Hw8BhHaNiR2zedYEvOKug8jimNOS/oyWEjrV4P8UYkshleZ7Y2C'
where SSO_ID = 'danny';

UPDATE APP_USER
SET PASSWORD = '$2a$10$Q9xo8/lGqhj33qM7HSBtsenVGVQJg/hVVwQHHUM8DW5sViLN/D3kK'
where SSO_ID = 'sam';

UPDATE APP_USER
SET PASSWORD = '$2a$10$c.jrCzunpwzAFcWCALdglO4oAsLTGpFoHFAGg6gS.AACOUrj0G5yC'
where SSO_ID = 'nicole';

UPDATE APP_USER
SET PASSWORD = '$2a$10$xn7pzg0Wpd5ViDsDHUB4v.CQutvNTdxJji.yLa6bFZK6YxafgHpLy'
where SSO_ID = 'kenny';

UPDATE APP_USER
SET PASSWORD = '$2a$10$24XRBJNPnTe8sI5QDUP5guwXjnQtmp.M9UN6Kbe2NPCVpAuaPbddi'
where SSO_ID = 'sudo';

UPDATE APP_USER
SET PASSWORD = '$2a$10$G8gZdRyr/La58d6I9g4P1evu9Oe27bH04Alef9FNh7ktUMqmjkYpG'
where SSO_ID = 'tsuser';

UPDATE APP_USER
SET PASSWORD = '$2a$10$xgMc9btS6p.ulee42dKf3.dHQar1J8i.j11M4GXDUGYvLyFup4Cvq'
where SSO_ID = 'admin';
