RENAME TABLE RECHARGE TO PAYMENT;

SET @RECHARGE_SEQUENCE := (SELECT SEQ_NUMBER FROM SEQUENCES WHERE SEQ_NAME = 'RECHARGE_SEQUENCE');
SELECT @RECHARGE_SEQUENCE;
INSERT INTO SEQUENCES VALUES ('PAYMENT_SEQUENCE', @RECHARGE_SEQUENCE);

DELETE FROM SEQUENCES WHERE SEQ_NAME = 'RECHARGE_SEQUENCE';
