/*
 * Created under not commercial project "Make it fine"
 *
 * Copyright 2017-2020
 */

package com.stingion.yaypay.data.model;

import com.stingion.yaypay.data.model.tables.Book;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class JooqDb extends SchemaImpl {

    private static final long serialVersionUID = 79555318;

    /**
     * The reference instance of <code>jooq_db</code>
     */
    public static final JooqDb JOOQ_DB = new JooqDb();

    /**
     * The table <code>jooq_db.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * No further instances allowed
     */
    private JooqDb() {
        super("jooq_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Book.BOOK);
    }
}
