ALTER TABLE RECHARGE RENAME TO PAYMENT;

INSERT INTO SEQUENCES VALUES ('PAYMENT_SEQUENCE',
                              (SELECT SEQ_NUMBER FROM SEQUENCES WHERE SEQ_NAME = 'RECHARGE_SEQUENCE'));

DELETE FROM SEQUENCES WHERE SEQ_NAME = 'RECHARGE_SEQUENCE';
