/* USER_PROFILE table contains all possible roles */
CREATE TABLE USER_PROFILE (
  ID INT NOT NULL,
  type VARCHAR(30) NOT NULL,
  CONSTRAINT USER_PROFILE_PK PRIMARY KEY (ID)
  ENABLE
);

CREATE TABLE SEQUENCES (
  SEQ_NAME VARCHAR(80) NOT NULL,
  SEQ_NUMBER INT NOT NULL,
  CONSTRAINT SEQUENCES_PK PRIMARY KEY (SEQ_NAME)
  ENABLE
);

INSERT INTO USER_PROFILE VALUES (1, 'USER');
INSERT INTO User_Profile VALUES (2, 'ADMIN');
INSERT INTO User_Profile VALUES (3, 'DBA');

INSERT INTO SEQUENCES VALUES('USER_PROFILE_SEQUENCE', 4);