CREATE TABLE BANK (
  ID   INT NOT NULL,
  NAME VARCHAR(30) UNIQUE,
  PRIMARY KEY (ID)
);

INSERT INTO BANK VALUES (1, 'Unicredit');
INSERT INTO BANK VALUES (2, 'Raiffeisen');
INSERT INTO BANK VALUES (3, 'PrivatBank');
INSERT INTO BANK VALUES (4, 'UkrSibbank');
INSERT INTO BANK VALUES (5, 'Platinum Bank');

INSERT INTO SEQUENCES VALUES ('BANK_SEQUENCE', 4);

CREATE TABLE CREDIT_CARD (
  ID         INT NOT NULL,
  NUMBER     BIGINT UNIQUE,
  TYPE       ENUM ('MasterCard', 'Visa'),
  BANK_ID    INT,
  CONTACT_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (BANK_ID) REFERENCES BANK (ID)
);

INSERT INTO CREDIT_CARD VALUES (1, 1234571277518812, 'MasterCard',
  (SELECT ID FROM BANK WHERE NAME = 'PrivatBank'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'bill@xyz.com')
);
INSERT INTO CREDIT_CARD VALUES (2, 6647486058945594, 'Visa',
  (SELECT ID FROM BANK WHERE NAME = 'Unicredit'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'danny@xyz.com')
);
INSERT INTO CREDIT_CARD VALUES (3, 2237435131126577, 'Visa',
  (SELECT ID FROM BANK WHERE NAME = 'Raiffeisen'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'samy@xyz.com')
);
INSERT INTO CREDIT_CARD VALUES (4, 1123729594138004, 'MasterCard',
  (SELECT ID FROM BANK WHERE NAME = 'UkrSibbank'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'nicloe@xyz.com')
);
INSERT INTO CREDIT_CARD VALUES (5, 6541296068298653, 'Visa',
  (SELECT ID FROM BANK WHERE NAME = 'Platinum Bank'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'kenny@xyz.com')
);
INSERT INTO CREDIT_CARD VALUES (6, 5923542550577566, 'MasterCard',
  (SELECT ID FROM BANK WHERE NAME = 'Platinum Bank'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'sudo@xxx.xxx')
);
INSERT INTO CREDIT_CARD VALUES (7, 7970188838706486, 'Visa',
  (SELECT ID FROM BANK WHERE NAME = 'Unicredit'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'tsuser@xxx.xxx')
);
INSERT INTO CREDIT_CARD VALUES (8,  2184747417855136, 'Visa',
  (SELECT ID FROM BANK WHERE NAME = 'PrivatBank'),
  (SELECT ID FROM APP_USER WHERE EMAIL = 'admin@xxx.xxx')
);

INSERT INTO SEQUENCES VALUES ('CREDIT_CARD_SEQUENCE', 9);

CREATE TABLE ITEM (
  ID INT NOT NULL,
  HEADER VARCHAR(80) UNIQUE,
  PRICE DOUBLE,
  PRIMARY KEY (ID)
);

INSERT INTO ITEM VALUES (1, 'Repair room', 100);
INSERT INTO ITEM VALUES (2, 'Repair bathroom', 150);
INSERT INTO ITEM VALUES (3, 'Build garage', 1500);
INSERT INTO ITEM VALUES (4, 'Repair tap', 25.5);
INSERT INTO ITEM VALUES (5, 'Install plumber', 40);

INSERT INTO SEQUENCES VALUES ('ITEM_SEQUENCE', 6);

CREATE TABLE `ORDERING` (
  ID INT NOT NULL,
  DESCRIPTION VARCHAR(100),
  STATUS ENUM('Pending', 'Performed', 'Cancelled'),
  ITEM_ID INT,
  CREDIT_CARD_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (CREDIT_CARD_ID) REFERENCES CREDIT_CARD (ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

INSERT INTO `ORDERING` VALUES (1, 'Deliver to Kyiv, Melnyka 35/5', 'PENDING',
  (SELECT ID FROM ITEM WHERE HEADER = 'Repair room'),
  (SELECT ID FROM CREDIT_CARD WHERE NUMBER = 2184747417855136)
);

INSERT INTO `ORDERING` VALUES (2, 'Deliver to Myshkova, Stynova 15/15 after 18:00', 'PENDING',
  (SELECT ID FROM ITEM WHERE HEADER = 'Repair bathroom'),
  (SELECT ID FROM CREDIT_CARD WHERE NUMBER = 7970188838706486)
);
INSERT INTO `ORDERING` VALUES (3, 'Deliver to Kyiv, Strilsova 11/11', 'PENDING',
  (SELECT ID FROM ITEM WHERE HEADER = 'Build garage'),
  (SELECT ID FROM CREDIT_CARD WHERE NUMBER = 6541296068298653)
);
INSERT INTO `ORDERING` VALUES (4, 'Cancelled cause of subjective reason', 'CANCELLED',
  (SELECT ID FROM ITEM WHERE HEADER = 'Repair tap'),
  (SELECT ID FROM CREDIT_CARD WHERE NUMBER = 5923542550577566)
);
INSERT INTO `ORDERING` VALUES (5, 'Delivered to Kyiv, Smirnova 25/101', 'PERFORMED',
  (SELECT ID FROM ITEM WHERE HEADER = 'Install plumber'),
  (SELECT ID FROM CREDIT_CARD WHERE NUMBER = 1234571277518812)
);

INSERT INTO SEQUENCES VALUES ('ORDERING_SEQUENCE', 6);
